### ISSUE TITLE
compose.ps1 does not work on a Mac

### ISSUE THREAD

**Issue by delostilos** [CrossBreezeNL/PowerDesigner-MDDE-Extension#1]
I've installed PowerShell via brew. If I run ./compose.ps1 in PowerShell the path's are wrong:

Error: Unable to access jarfile /Users/datadenken/Documents/GitHub/PowerDesigner-MDDE-Extension/pdc\PowerDeComposer.jar

If I change the back slashes to forward slashes in the paths in the PowerShell scripts the compose.ps1 script works.
Although I get unexpected empty log files in the decomposed folders.

I do not know if the scripts with forward slashes still work on a Windows system.

**Comment by harmen-xb** [comment]
@delostilos I have refactored all paths to use Join-Path i.s.o. literals with a backslash. Can you check whether it is solved now?

**Comment by delostilos** [comment]
Yes, it works now. Thanks.
