### ISSUE TITLE
<Extended Sub-Object> is not a valid XML tag.

### ISSUE THREAD

**Issue by delostilos** [CrossBreezeNL/PowerDesigner-MDDE-Extension#2]
When exporting the ExampleDWH to the EXAMPLEDWH.model.xml it generates the <Extended Sub-Object> tag. 
Whitespaces are not allowed in XML element or attribute names: https://www.w3.org/TR/xml/#NT-NameStartChar
So we should remove the space in the element name.

**Comment by Moo925** [comment]
This is fixed now. Check this [commit](https://github.com/CrossBreezeNL/PowerDesigner-MDDE-Extension/commit/b020b63338f5f13a067d041736fb5a9079d9fc6f)
To get the new changes you need to pull the changes from github into your project

**Comment by harmen-xb** [comment]
There was another issue in the export due to the prefix rename of all extended stuff in the XEM. Stereotypes where not exported correctly in the XML (Extended Sub-Object shouldn't have been part of the export). This is fixed now.
