### ISSUE TITLE
The relationships are being created on the LDM model on the outgoing and incoming entities. They should be created only on the outgoing entity.

### ISSUE THREAD

**Issue by Moo925** [CrossBreezeNL/PowerDesigner-MDDE-Extension#3]

**Comment by harmen-xb** [comment]
It's not that easy to fix this, relationships in an LDM can be n-to-n. So in this case I think we should mention the relationship on both sides. In all other cases we can mention the relationship only on the outgoing side.

**Comment by harmen-xb** [comment]
Untill now no user is experiencing issues with the current metadata export. So closing issue for now.
