### ISSUE TITLE
ObjectPicker gives error when using the extension in PowerDesigner 16.5

### ISSUE THREAD

**Issue by delostilos** [CrossBreezeNL/PowerDesigner-MDDE-Extension#8]
When using the MDDE extension in version 16.5 of PowerDesigner the ObjectPicker gives an error when creating a mapping:

![image](https://user-images.githubusercontent.com/2998787/236821790-23cd6502-8b55-4974-a58c-305b3146c999.png)

**Comment by harmenwessels** [comment]
@delostilos Can you send a screenshot of the ShowObjectPicker method signature according to the docs in your PowerDesigner version?

Then I can compare it with newer versions and see what's different.

**Comment by delostilos** [comment]
In 16.5 it does not have the last parameter: ByVal ExcludedCurrentModel As Boolean = False

**Comment by harmen-xb** [comment]
For now we decided not to support PowerDesigner 16.5, since all users are using PowerDesigner >= 16.6.
